---
- name: Database Setup
  hosts: dbservers
  remote_user: root
  roles:
          - database


- name: webservers setup
  hosts: webservers
  remote_user: root
  roles:
          - apache
          - php
          - wordpress



