---
- name: mariadb | install mariadb server
  package: name=mariadb-server state=present

- name: maridb | install mariadb client
  package: name=mariadb-client state=present


- name : database | install mariadb Mysql
  package: name=python-mysqldb state=present

- name: database | Set root Password
  mysql_user: login_password={{ root_password }} check_implicit_admin=yes name=root host={{ item }} password={{ root_password }} state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: database | Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: database | Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: database | Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False


- name: database |  Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: database | Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  ####################################################################

# create wordpress database and database user

- name: database | create database for wordpress
  mysql_db:
        name: wpdb
        state: present

        #- name: database | create user and grant the user full access to the database        
- mysql_user:
        name: "{{ wpdb_user }}"
        password: "{{ wpdb_password }}"
        priv: 'wpdb.*:ALL'
        state: present

- name: database | Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False



